chore: speed up npu ci caching

diff --git a/ci/Dockerfile b/ci/Dockerfile
--- a/ci/Dockerfile
+++ b/ci/Dockerfile
@@ -1,6 +1,7 @@
 FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:8.5.0-910b-ubuntu22.04-py3.10-ops
 
 ARG INSTALL_TEST_REQUIREMENTS=false
+ARG PREWARM_THIRD_PARTY=true
 
 ENV DEBIAN_FRONTEND=noninteractive \
     ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest \
@@ -24,6 +25,7 @@ RUN apt-get update && \
       make \
       ninja-build \
       openssh-client \
+      patch \
       pkg-config \
       python3-dev \
       python3-pip \
@@ -45,6 +47,49 @@ RUN python3 -m pip install --upgrade pip setuptools wheel && \
     if [[ "${INSTALL_TEST_REQUIREMENTS}" == "true" ]]; then \
       grep -v -E '^[[:space:]]*(#|$|valgrind[[:space:]]*$)' /tmp/fla-ci/tests-requirements.txt \
         | python3 -m pip install -r /dev/stdin; \
+    fi
+
+RUN if [[ "${PREWARM_THIRD_PARTY}" == "true" ]]; then \
+      mkdir -p /opt/fla-ci/third_party/pkg; \
+      download() { \
+        local url="$1"; \
+        local dest="$2"; \
+        if [[ -s "$dest" ]]; then return 0; fi; \
+        echo "[CI][prewarm] downloading $url"; \
+        if ! curl -fL --retry 3 --retry-delay 2 -o "$dest" "$url"; then \
+          echo "[CI][prewarm][WARN] failed to download $url"; \
+          rm -f "$dest"; \
+        fi; \
+      }; \
+      clone_at() { \
+        local url="$1"; \
+        local rev="$2"; \
+        local dest="$3"; \
+        if [[ -d "$dest/.git" ]]; then return 0; fi; \
+        echo "[CI][prewarm] cloning $url"; \
+        if git clone "$url" "$dest" && git -C "$dest" checkout "$rev"; then \
+          true; \
+        else \
+          echo "[CI][prewarm][WARN] failed to clone $url"; \
+          rm -rf "$dest"; \
+        fi; \
+      }; \
+      download "https://gitcode.com/cann-src-third-party/eigen/releases/download/5.0.0-h0.trunk/eigen-5.0.0.tar.gz" \
+        /opt/fla-ci/third_party/pkg/eigen-5.0.0.tar.gz; \
+      download "https://gitcode.com/cann-src-third-party/abseil-cpp/releases/download/20230802.1/abseil-cpp-20230802.1.tar.gz" \
+        /opt/fla-ci/third_party/pkg/abseil-cpp-20230802.1.tar.gz; \
+      download "https://gitcode.com/cann-src-third-party/protobuf/releases/download/v25.1/protobuf-25.1.tar.gz" \
+        /opt/fla-ci/third_party/pkg/protobuf-25.1.tar.gz; \
+      download "https://gitcode.com/cann-src-third-party/makeself/releases/download/release-2.5.0-patch1.0/makeself-release-2.5.0-patch1.tar.gz" \
+        /opt/fla-ci/third_party/pkg/makeself-release-2.5.0-patch1.tar.gz; \
+      download "https://gitcode.com/cann-src-third-party/json/releases/download/v3.11.3/include.zip" \
+        /opt/fla-ci/third_party/pkg/include.zip; \
+      clone_at "https://gitcode.com/cann/opbase.git" \
+        c8d83f3e57a63a7375e89a2d6937452c0ae2e522 \
+        /opt/fla-ci/third_party/opbase; \
+      clone_at "https://gitcode.com/cann/catlass.git" \
+        41bf90da655bba3c66d0acd7e00abe33960ecfd6 \
+        /opt/fla-ci/third_party/catlass; \
     fi
 
 WORKDIR /workspace/repo
